import type {
  AiPolicy,
  AuditLogEntry,
  Channel,
  ChannelKind,
  Conversation,
  ConversationMessage,
  MessageEvent,
  OutboxItem,
  PipelineStageStats,
  RecentIncident,
  SopWorkflow,
  TrafficPoint,
} from "./types";

export const CHANNEL_META: Record<
  ChannelKind,
  { label: string; color: string }
> = {
  wecom: { label: "WeCom", color: "#2AA245" },
  feishu: { label: "Feishu", color: "#3370FF" },
  dingtalk: { label: "DingTalk", color: "#1E90FF" },
  whatsapp: { label: "WhatsApp", color: "#25D366" },
  telegram: { label: "Telegram", color: "#29A9EA" },
  email: { label: "Email", color: "#64748B" },
};

const now = Date.now();
const minutesAgo = (m: number) => new Date(now - m * 60_000).toISOString();

export const channels: Channel[] = [
  {
    id: "ch_wecom",
    kind: "wecom",
    name: "WeCom — Sales Workspace",
    status: "connected",
    receiveCapabilities: ["webhook"],
    sendCapabilities: ["api"],
    lastSyncAt: minutesAgo(1),
    errorCount24h: 2,
    messagesToday: 4218,
    activeConversations: 312,
  },
  {
    id: "ch_feishu",
    kind: "feishu",
    name: "Feishu — Customer Success",
    status: "connected",
    receiveCapabilities: ["webhook"],
    sendCapabilities: ["api"],
    lastSyncAt: minutesAgo(2),
    errorCount24h: 0,
    messagesToday: 2854,
    activeConversations: 201,
  },
  {
    id: "ch_dingtalk",
    kind: "dingtalk",
    name: "DingTalk — Partner Channel",
    status: "degraded",
    receiveCapabilities: ["webhook", "polling"],
    sendCapabilities: ["api", "manual_approval"],
    lastSyncAt: minutesAgo(18),
    errorCount24h: 47,
    messagesToday: 963,
    activeConversations: 84,
  },
  {
    id: "ch_whatsapp",
    kind: "whatsapp",
    name: "WhatsApp Business",
    status: "connected",
    receiveCapabilities: ["webhook"],
    sendCapabilities: ["api"],
    lastSyncAt: minutesAgo(1),
    errorCount24h: 5,
    messagesToday: 3109,
    activeConversations: 265,
  },
  {
    id: "ch_telegram",
    kind: "telegram",
    name: "Telegram Bot — Community",
    status: "connected",
    receiveCapabilities: ["webhook"],
    sendCapabilities: ["api"],
    lastSyncAt: minutesAgo(3),
    errorCount24h: 1,
    messagesToday: 1542,
    activeConversations: 118,
  },
  {
    id: "ch_email_rpa",
    kind: "email",
    name: "Email — Support Mailbox (RPA)",
    status: "disabled",
    receiveCapabilities: ["polling", "rpa"],
    sendCapabilities: ["rpa", "manual_approval"],
    lastSyncAt: minutesAgo(540),
    errorCount24h: 0,
    messagesToday: 0,
    activeConversations: 0,
  },
];

export const pipelineStats: PipelineStageStats[] = [
  { stage: "connector", label: "Connector", throughputPerMin: 214, failures1h: 3, avgLatencyMs: 82 },
  { stage: "ingest", label: "Ingest", throughputPerMin: 211, failures1h: 2, avgLatencyMs: 46 },
  { stage: "normalize", label: "Normalize", throughputPerMin: 209, failures1h: 1, avgLatencyMs: 34 },
  { stage: "store", label: "Store", throughputPerMin: 209, failures1h: 0, avgLatencyMs: 21 },
  { stage: "sop_ai", label: "SOP / AI", throughputPerMin: 187, failures1h: 6, avgLatencyMs: 640 },
  { stage: "outbox", label: "Outbox", throughputPerMin: 164, failures1h: 4, avgLatencyMs: 118 },
  { stage: "delivery", label: "Delivery", throughputPerMin: 159, failures1h: 5, avgLatencyMs: 245 },
];

const eventTypes = [
  "message.received",
  "message.sent",
  "message.delivered",
  "message.failed",
  "sop.step.completed",
  "ai.reply_drafted",
  "ai.handoff_triggered",
];

const chKinds: ChannelKind[] = ["wecom", "feishu", "dingtalk", "whatsapp", "telegram", "email"];

function seedRandom(seed: number) {
  let s = seed;
  return () => {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
}

const rnd = seedRandom(42);

export const messageEvents: MessageEvent[] = Array.from({ length: 64 }).map((_, i) => {
  const status: MessageEvent["status"] =
    rnd() > 0.9 ? "failed" : rnd() > 0.85 ? "retrying" : rnd() > 0.8 ? "pending" : "success";
  return {
    id: `evt_${1000 + i}`,
    time: minutesAgo(Math.floor(rnd() * 240)),
    channel: chKinds[Math.floor(rnd() * chKinds.length)],
    direction: rnd() > 0.5 ? "inbound" : "outbound",
    conversationId: `conv_${100 + Math.floor(rnd() * 40)}`,
    conversationLabel: `Conversation #${100 + Math.floor(rnd() * 40)}`,
    eventType: eventTypes[Math.floor(rnd() * eventTypes.length)],
    status,
    latencyMs: Math.floor(40 + rnd() * 900),
    traceId: `trace-${(100000 + Math.floor(rnd() * 899999)).toString(16)}`,
  };
});

export const conversations: Conversation[] = [
  {
    id: "conv_101",
    channel: "wecom",
    contactName: "Li Wei",
    contactHandle: "@liwei_procurement",
    lastMessagePreview: "能否提供一下最新的报价单和付款条款？",
    lastMessageAt: minutesAgo(4),
    assignedOperator: "Sarah Chen",
    aiStatus: "auto_replying",
    sopStage: "in_progress",
    sopWorkflowName: "Enterprise Quote Approval",
    unread: 2,
    tags: ["enterprise", "quote"],
  },
  {
    id: "conv_102",
    channel: "whatsapp",
    contactName: "Maria Gonzalez",
    contactHandle: "+52 55 1234 0098",
    lastMessagePreview: "The tracking number hasn't updated in 3 days.",
    lastMessageAt: minutesAgo(9),
    assignedOperator: null,
    aiStatus: "handed_off",
    sopStage: "waiting_human",
    sopWorkflowName: "Shipping Escalation",
    unread: 1,
    tags: ["logistics", "escalation"],
  },
  {
    id: "conv_103",
    channel: "feishu",
    contactName: "Zhang Min",
    contactHandle: "@zhangmin",
    lastMessagePreview: "已经确认合同条款，等待盖章。",
    lastMessageAt: minutesAgo(21),
    assignedOperator: "Wei Zhao",
    aiStatus: "monitoring",
    sopStage: "completed",
    sopWorkflowName: "Contract Signing",
    unread: 0,
    tags: ["contract"],
  },
  {
    id: "conv_104",
    channel: "telegram",
    contactName: "Alex Petrov",
    contactHandle: "@alexp",
    lastMessagePreview: "Is there a way to integrate with our own CRM?",
    lastMessageAt: minutesAgo(33),
    assignedOperator: "Sarah Chen",
    aiStatus: "auto_replying",
    sopStage: "none",
    sopWorkflowName: null,
    unread: 0,
    tags: ["pre-sales"],
  },
  {
    id: "conv_105",
    channel: "dingtalk",
    contactName: "Chen Hao",
    contactHandle: "@chenhao_partner",
    lastMessagePreview: "对接文档中的鉴权部分有个问题",
    lastMessageAt: minutesAgo(58),
    assignedOperator: null,
    aiStatus: "idle",
    sopStage: "failed",
    sopWorkflowName: "Partner Onboarding",
    unread: 3,
    tags: ["partner", "technical"],
  },
  {
    id: "conv_106",
    channel: "email",
    contactName: "Support Ticket #8821",
    contactHandle: "j.turner@acme-corp.com",
    lastMessagePreview: "Following up on the refund request submitted last week.",
    lastMessageAt: minutesAgo(72),
    assignedOperator: "Wei Zhao",
    aiStatus: "handed_off",
    sopStage: "waiting_human",
    sopWorkflowName: "Refund Processing",
    unread: 0,
    tags: ["billing"],
  },
  {
    id: "conv_107",
    channel: "whatsapp",
    contactName: "Fatima Al-Sayed",
    contactHandle: "+971 50 220 3344",
    lastMessagePreview: "Perfect, thank you for the quick response!",
    lastMessageAt: minutesAgo(96),
    assignedOperator: "Sarah Chen",
    aiStatus: "monitoring",
    sopStage: "completed",
    sopWorkflowName: "Order Confirmation",
    unread: 0,
    tags: ["order"],
  },
];

export const conversationMessages: ConversationMessage[] = [
  {
    id: "m1",
    conversationId: "conv_101",
    channel: "wecom",
    direction: "inbound",
    author: "Li Wei",
    content: "您好，我们想了解一下企业版的报价方案。",
    time: minutesAgo(40),
  },
  {
    id: "m2",
    conversationId: "conv_101",
    channel: "wecom",
    direction: "outbound",
    author: "AI Assistant",
    content: "您好 Li Wei，已为您整理企业版报价方案，包含席位数与年费明细，稍后发送 PDF 文件。",
    time: minutesAgo(38),
    isAiGenerated: true,
  },
  {
    id: "m3",
    conversationId: "conv_101",
    channel: "wecom",
    direction: "inbound",
    author: "Li Wei",
    content: "能否提供一下最新的报价单和付款条款？",
    time: minutesAgo(4),
  },
];

export const aiPolicies: AiPolicy[] = [
  {
    id: "pol_1",
    kind: "intent_classification",
    name: "Inbound Intent Classifier",
    enabled: true,
    priority: 1,
    triggerCondition: "On every inbound message",
    fallbackStrategy: "Route to default queue",
    successRate7d: 0.97,
    invocations24h: 8420,
  },
  {
    id: "pol_2",
    kind: "risk_detection",
    name: "Compliance & Risk Screening",
    enabled: true,
    priority: 1,
    triggerCondition: "Message contains financial or legal terms",
    fallbackStrategy: "Flag for human review, block auto-reply",
    successRate7d: 0.99,
    invocations24h: 612,
  },
  {
    id: "pol_3",
    kind: "reply_drafting",
    name: "Sales Reply Drafting",
    enabled: true,
    priority: 2,
    triggerCondition: "Intent = pre-sales AND confidence > 0.8",
    fallbackStrategy: "Draft only, require operator approval",
    successRate7d: 0.91,
    invocations24h: 2140,
  },
  {
    id: "pol_4",
    kind: "knowledge_retrieval",
    name: "Product Knowledge Retrieval",
    enabled: true,
    priority: 2,
    triggerCondition: "Question matches knowledge base topics",
    fallbackStrategy: "Fall back to human handoff",
    successRate7d: 0.94,
    invocations24h: 3305,
  },
  {
    id: "pol_5",
    kind: "tool_calling",
    name: "Order Status Lookup",
    enabled: true,
    priority: 3,
    triggerCondition: "Intent = order_status",
    fallbackStrategy: "Retry once, then escalate",
    successRate7d: 0.88,
    invocations24h: 1876,
  },
  {
    id: "pol_6",
    kind: "human_handoff",
    name: "Escalation Handoff Policy",
    enabled: true,
    priority: 1,
    triggerCondition: "Risk flag OR sentiment < -0.6 OR SLA breach imminent",
    fallbackStrategy: "Assign to on-call operator",
    successRate7d: 0.99,
    invocations24h: 214,
  },
  {
    id: "pol_7",
    kind: "auto_reply_policy",
    name: "After-hours Auto Reply",
    enabled: false,
    priority: 4,
    triggerCondition: "Outside business hours AND no operator online",
    fallbackStrategy: "Queue for next business day",
    successRate7d: 0.95,
    invocations24h: 0,
  },
];

export const sopWorkflows: SopWorkflow[] = [
  {
    id: "wf_1",
    name: "Enterprise Quote Approval",
    trigger: "Intent = pricing_request AND deal_size > 50k",
    channels: ["wecom", "feishu"],
    activeConversations: 18,
    completionRate: 0.86,
    slaMinutes: 240,
    status: "active",
    steps: [
      {
        id: "s1",
        name: "Classify request",
        condition: "Inbound message received",
        aiAction: "Classify intent and extract deal size",
        humanAction: null,
        timeoutMinutes: 2,
        fallback: "Route to manual triage",
      },
      {
        id: "s2",
        name: "Generate quote draft",
        condition: "Intent confirmed as pricing_request",
        aiAction: "Draft quote from pricing table",
        humanAction: null,
        timeoutMinutes: 5,
        fallback: "Notify sales ops",
      },
      {
        id: "s3",
        name: "Sales approval",
        condition: "Quote draft ready",
        aiAction: null,
        humanAction: "Sales manager reviews and approves discount",
        timeoutMinutes: 120,
        fallback: "Escalate to regional director",
      },
      {
        id: "s4",
        name: "Send to customer",
        condition: "Quote approved",
        aiAction: "Send PDF via original channel",
        humanAction: null,
        timeoutMinutes: 5,
        fallback: "Retry delivery, then alert operator",
      },
    ],
  },
  {
    id: "wf_2",
    name: "Shipping Escalation",
    trigger: "Intent = shipping_delay AND days_delayed > 2",
    channels: ["whatsapp", "email"],
    activeConversations: 7,
    completionRate: 0.72,
    slaMinutes: 60,
    status: "active",
    steps: [
      {
        id: "s1",
        name: "Verify tracking status",
        condition: "Escalation triggered",
        aiAction: "Call logistics API for latest tracking event",
        humanAction: null,
        timeoutMinutes: 3,
        fallback: "Escalate directly to human",
      },
      {
        id: "s2",
        name: "Customer support review",
        condition: "Tracking confirms delay",
        aiAction: null,
        humanAction: "Support agent contacts carrier",
        timeoutMinutes: 45,
        fallback: "Escalate to logistics manager",
      },
    ],
  },
  {
    id: "wf_3",
    name: "Partner Onboarding",
    trigger: "New partner application submitted",
    channels: ["dingtalk"],
    activeConversations: 4,
    completionRate: 0.64,
    slaMinutes: 1440,
    status: "paused",
    steps: [
      {
        id: "s1",
        name: "Document collection",
        condition: "Application received",
        aiAction: "Send required document checklist",
        humanAction: null,
        timeoutMinutes: 60,
        fallback: "Remind after 24h",
      },
      {
        id: "s2",
        name: "Technical review",
        condition: "Documents complete",
        aiAction: null,
        humanAction: "Solutions engineer reviews integration plan",
        timeoutMinutes: 720,
        fallback: "Escalate to partner manager",
      },
    ],
  },
  {
    id: "wf_4",
    name: "Refund Processing",
    trigger: "Intent = refund_request",
    channels: ["email", "wecom"],
    activeConversations: 11,
    completionRate: 0.9,
    slaMinutes: 180,
    status: "active",
    steps: [
      {
        id: "s1",
        name: "Validate order",
        condition: "Refund requested",
        aiAction: "Look up order and refund eligibility",
        humanAction: null,
        timeoutMinutes: 3,
        fallback: "Flag for manual check",
      },
      {
        id: "s2",
        name: "Finance approval",
        condition: "Eligible for refund",
        aiAction: null,
        humanAction: "Finance approves refund amount",
        timeoutMinutes: 120,
        fallback: "Escalate to finance lead",
      },
      {
        id: "s3",
        name: "Confirm to customer",
        condition: "Refund processed",
        aiAction: "Send confirmation message",
        humanAction: null,
        timeoutMinutes: 5,
        fallback: "Retry send",
      },
    ],
  },
  {
    id: "wf_5",
    name: "Order Confirmation",
    trigger: "New order created",
    channels: ["whatsapp", "telegram"],
    activeConversations: 22,
    completionRate: 0.97,
    slaMinutes: 15,
    status: "draft",
    steps: [
      {
        id: "s1",
        name: "Send confirmation",
        condition: "Order created event received",
        aiAction: "Send order summary and ETA",
        humanAction: null,
        timeoutMinutes: 2,
        fallback: "Retry twice, then notify ops",
      },
    ],
  },
];

export const outboxItems: OutboxItem[] = [
  {
    id: "out_1",
    createdAt: minutesAgo(2),
    channel: "wecom",
    conversationId: "conv_101",
    conversationLabel: "Li Wei — Enterprise Quote",
    messageType: "Document",
    sender: "AI Assistant",
    deliveryMethod: "api",
    status: "sending",
    retryCount: 0,
    lastError: null,
  },
  {
    id: "out_2",
    createdAt: minutesAgo(6),
    channel: "dingtalk",
    conversationId: "conv_105",
    conversationLabel: "Chen Hao — Partner Onboarding",
    messageType: "Text",
    sender: "System",
    deliveryMethod: "rpa",
    status: "failed",
    retryCount: 3,
    lastError: "RPA session timeout after 30s",
  },
  {
    id: "out_3",
    createdAt: minutesAgo(11),
    channel: "email",
    conversationId: "conv_106",
    conversationLabel: "Ticket #8821 — Refund",
    messageType: "Email",
    sender: "Wei Zhao",
    deliveryMethod: "manual_approval",
    status: "requires_approval",
    retryCount: 0,
    lastError: null,
  },
  {
    id: "out_4",
    createdAt: minutesAgo(14),
    channel: "whatsapp",
    conversationId: "conv_102",
    conversationLabel: "Maria Gonzalez — Shipping",
    messageType: "Text",
    sender: "AI Assistant",
    deliveryMethod: "api",
    status: "sent",
    retryCount: 0,
    lastError: null,
  },
  {
    id: "out_5",
    createdAt: minutesAgo(19),
    channel: "telegram",
    conversationId: "conv_104",
    conversationLabel: "Alex Petrov — Pre-sales",
    messageType: "Text",
    sender: "AI Assistant",
    deliveryMethod: "api",
    status: "pending",
    retryCount: 0,
    lastError: null,
  },
  {
    id: "out_6",
    createdAt: minutesAgo(26),
    channel: "feishu",
    conversationId: "conv_103",
    conversationLabel: "Zhang Min — Contract",
    messageType: "Card",
    sender: "System",
    deliveryMethod: "api",
    status: "sent",
    retryCount: 1,
    lastError: null,
  },
  {
    id: "out_7",
    createdAt: minutesAgo(31),
    channel: "whatsapp",
    conversationId: "conv_107",
    conversationLabel: "Fatima Al-Sayed — Order",
    messageType: "Text",
    sender: "AI Assistant",
    deliveryMethod: "api",
    status: "failed",
    retryCount: 2,
    lastError: "Recipient number opted out of messages",
  },
];

export const auditLog: AuditLogEntry[] = [
  {
    id: "aud_1",
    time: minutesAgo(3),
    actor: "Sarah Chen",
    actorType: "user",
    action: "Approved outbound message",
    target: "out_3",
    channel: "email",
    result: "success",
    ip: "10.20.4.18",
  },
  {
    id: "aud_2",
    time: minutesAgo(12),
    actor: "AI Assistant",
    actorType: "ai",
    action: "Drafted reply",
    target: "conv_101",
    channel: "wecom",
    result: "success",
    ip: null,
  },
  {
    id: "aud_3",
    time: minutesAgo(24),
    actor: "System",
    actorType: "system",
    action: "Disabled channel due to repeated failures",
    target: "ch_email_rpa",
    channel: "email",
    result: "success",
    ip: null,
  },
  {
    id: "aud_4",
    time: minutesAgo(40),
    actor: "Wei Zhao",
    actorType: "user",
    action: "Updated SOP workflow",
    target: "wf_3",
    channel: null,
    result: "success",
    ip: "10.20.4.42",
  },
  {
    id: "aud_5",
    time: minutesAgo(58),
    actor: "System",
    actorType: "system",
    action: "API key rotation failed",
    target: "ch_dingtalk",
    channel: "dingtalk",
    result: "failure",
    ip: null,
  },
];

export const recentIncidents: RecentIncident[] = [
  {
    id: "inc_1",
    time: minutesAgo(18),
    severity: "warning",
    summary: "DingTalk webhook latency exceeded 5s threshold",
    channel: "dingtalk",
  },
  {
    id: "inc_2",
    time: minutesAgo(52),
    severity: "critical",
    summary: "Email RPA connector disabled after 12 consecutive failures",
    channel: "email",
  },
  {
    id: "inc_3",
    time: minutesAgo(95),
    severity: "info",
    summary: "WhatsApp template message rejected — outdated template ID",
    channel: "whatsapp",
  },
];

export const trafficSeries: TrafficPoint[] = Array.from({ length: 24 }).map((_, i) => {
  const hour = `${i.toString().padStart(2, "0")}:00`;
  const base = 300 + Math.sin(i / 2.4) * 120;
  return {
    hour,
    inbound: Math.max(20, Math.round(base + rnd() * 60)),
    outbound: Math.max(15, Math.round(base * 0.82 + rnd() * 50)),
  };
});

export const overviewStats = {
  activeChannels: channels.filter((c) => c.status !== "disabled").length,
  totalChannels: channels.length,
  messagesIngestedToday: channels.reduce((sum, c) => sum + c.messagesToday, 0),
  aiActionsToday: 6420,
  outboxPending: outboxItems.filter((o) => o.status === "pending" || o.status === "requires_approval").length,
  errorRate: 0.021,
  p95LatencyMs: 1180,
};
