// Task validation rule tables define the product task-create schema.
// They are kept separate from validation logic so future task type additions
// can be reviewed against contract drift in one small file.
package tasks

var topLevelFields = map[string]bool{
	"task_id":    true,
	"source":     true,
	"target":     true,
	"task_type":  true,
	"payload":    true,
	"created_at": true,
	"trace_id":   true,
}

var validSources = map[string]bool{
	"cloud-web":     true,
	"cloud-backend": true,
	"system":        true,
}

var validTaskTypes = map[string]bool{
	"send_text":                        true,
	"send_image":                       true,
	"send_video":                       true,
	"send_voice":                       true,
	"send_file":                        true,
	"group_invite":                     true,
	"appointment_billing":              true,
	"send_address":                     true,
	"request_money":                    true,
	"transfer_money":                   true,
	"rpa_voice_call":                   true,
	"rpa_video_call":                   true,
	"rpa_hangup_call":                  true,
	"rpa_prepare_call_audio_output":    true,
	"wework_voice_call":                true,
	"wework_video_call":                true,
	"wework_hangup_call":               true,
	"wework_prepare_call_audio_output": true,
	"send_mixed_messages":              true,
	"share_bundle_send":                true,
	"revoke_text_message":              true,
	"cancel_message":                   true,
	"connector_login_qrcode":           true,
	"connector_login_status":           true,
	"connector_login_verify":           true,
	"connector_user_info":              true,
	"connector_logout":                 true,
	"wework_login_qrcode":              true,
	"wework_login_status":              true,
	"wework_login_verify":              true,
	"wework_user_info":                 true,
	"wework_logout":                    true,
	"logout":                           true,
	"device_open_app":                  true,
	"device_stop_app":                  true,
	"device_screenshot":                true,
}

var payloadFields = map[string]bool{
	"username":                         true,
	"receiver":                         true,
	"receivers":                        true,
	"receiver_name":                    true,
	"conversation_id":                  true,
	"session_id":                       true,
	"sender_id":                        true,
	"customer_relation_status_at_send": true,
	"customer_deleted_current_member_at_send": true,
	"customer_relation_deleted_at":            true,
	"customer_relation_restored_at":           true,
	"text":                                    true,
	"media_url":                               true,
	"media_mime":                              true,
	"voice_duration_sec":                      true,
	"file":                                    true,
	"filename":                                true,
	"group_name":                              true,
	"aliases":                                 true,
	"entity":                                  true,
	"msg_id":                                  true,
	"order_id":                                true,
	"stage_unique_id":                         true,
	"remark":                                  true,
	"address":                                 true,
	"store_name":                              true,
	"store_id":                                true,
	"tencent_map_store":                       true,
	"button_name":                             true,
	"money":                                   true,
	"note":                                    true,
	"reason":                                  true,
	"target_trace_id":                         true,
	"target_content":                          true,
	"target_msg_type":                         true,
	"target_direction":                        true,
	"occurrence_from_bottom":                  true,
	"call_type":                               true,
	"messages":                                true,
	"queue":                                   true,
	"subprocess_timeout_sec":                  true,
	"no_progress_timeout_sec":                 true,
	"batch_id":                                true,
	"client_batch_id":                         true,
	"batch_index":                             true,
	"batch_total":                             true,
	"client_batch_index":                      true,
	"client_batch_total":                      true,
	"preserve_individual_send":                true,
	"share_mode":                              true,
	"ww_app_id":                               true,
	"ww_agent_id":                             true,
	"ww_schema":                               true,
	"share_app_name":                          true,
	"timeout_sec":                             true,
	"_send_policy":                            true,
	"verify_code":                             true,
	"app_id":                                  true,
	"package_name":                            true,
	"pkg":                                     true,
	"sop_audit":                               true,
	"verify_type":                             true,
	"timeout_seconds":                         true,
	"include_qrcode":                          true,
}

var taskRequiredPayloadFields = map[string][]string{
	"send_text":                        {"username", "text"},
	"send_image":                       {"username", "media_url"},
	"send_video":                       {"username", "media_url"},
	"send_file":                        {"username"},
	"group_invite":                     {"username", "group_name"},
	"appointment_billing":              {"username", "receiver", "entity", "msg_id"},
	"send_address":                     {"username", "receiver", "entity", "address", "button_name", "msg_id"},
	"request_money":                    {"username", "receiver", "entity", "money", "msg_id"},
	"transfer_money":                   {"username", "receiver", "entity", "msg_id", "note"},
	"send_voice":                       {"username", "media_url"},
	"rpa_voice_call":                   {"username", "receiver", "call_type"},
	"rpa_video_call":                   {"username", "receiver", "call_type"},
	"rpa_hangup_call":                  {"username", "receiver"},
	"rpa_prepare_call_audio_output":    {"username"},
	"wework_voice_call":                {"username", "receiver", "call_type"},
	"wework_video_call":                {"username", "receiver", "call_type"},
	"wework_hangup_call":               {"username", "receiver"},
	"wework_prepare_call_audio_output": {"username"},
	"send_mixed_messages":              {"username", "receiver", "entity", "msg_id", "messages"},
	"share_bundle_send":                {"username", "receiver", "entity", "msg_id", "messages", "share_mode"},
	"revoke_text_message":              {"username", "receiver", "target_trace_id", "target_content", "target_msg_type", "occurrence_from_bottom"},
	"cancel_message":                   {"username", "receiver", "entity", "msg_id"},
	"connector_login_verify":           {"username", "verify_code", "verify_type"},
	"wework_login_verify":              {"username", "verify_code", "verify_type"},
}

var messageItemFields = map[string]bool{
	"type":              true,
	"content":           true,
	"url":               true,
	"title":             true,
	"summary":           true,
	"description":       true,
	"icon":              true,
	"image":             true,
	"path":              true,
	"username":          true,
	"lat":               true,
	"lng":               true,
	"latitude":          true,
	"longitude":         true,
	"filename":          true,
	"address":           true,
	"store_name":        true,
	"store_id":          true,
	"tencent_map_store": true,
	"button_name":       true,
	"money":             true,
	"note":              true,
	"reason":            true,
	"stage_unique_id":   true,
}
